pipeline{
    agent any
    stages{
        stage('Build'){
            steps{
                git 'https://github.com/julietowah/inventory-management-system.git'
            }
            
        }
    }
}